name: Build and Push Docker Image

on:
  push:
    branches:
      - main-gk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v1

    - name: Checking current files in the directory 
      run: ls -l

    - name: Determine if image should be built
      id: should_build
      run: |
        if [[ "$GITHUB_REF" == "refs/heads/main-gk" || $(git log -1 --pretty=format:'%B' | grep -c "BUILD_CONTAINER_IMAGE") -gt 0 ]]; then
          echo "::set-output name=build::true"
        else
          echo "::set-output name=build::false"
        fi

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      id: build
      if: steps.should_build.outputs.build == 'true'
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ github.repository }}:latest
